### ISSUE TITLE
Consider warnings/errors when using deprecated functions

### ISSUE THREAD

**Issue by indigoxela** [backdrop-ops/phpcs#17]
This popped up as an idea in our Zulip chat.

Create a custom sniff to check for deprecated functions (note: deprecated in core).

This might make module ports slightly easier - find deprecated functions early and easily. Prevent drupal_set_message() or taxonomy_vocabulary_get_names() to slip through. :wink:

**Comment by indigoxela** [comment]
Now we have a [PR](https://github.com/backdrop-ops/phpcs/pull/18) for testing and discussion.

Hint: to only run this specific sniff, use `phpcs --sniffs=Backdrop.Functions.CoreDeprecatedFunctions *`.

**Comment by klonos** [comment]
Thanks @indigoxela 🙏🏼 ...this looks good 👍🏼 

I've left a couple of comments (double space between the variable and the `=`), although not sure if we follow the same coding standards as Drupal/Backdrop in the PHPCS code itself.

Lets allow a few more days to give others the opportunity to chime in, and then merge this.

**Comment by indigoxela** [comment]
> I've left a couple of comments

Fixed the white space issues. :+1: 

> Lets allow a few more days to give others the opportunity to chime in...

Sure, the main question's whether we want that to be in the ruleset, anyway. :wink:

**Comment by yorkshire-pudding** [comment]
Hi @indigoxela 

I've tested this and it works well
I agree that WARNING is the right level for this now. Will probably need to be set as an ERROR when checking for compatibility with 2.x.

**Comment by laryn** [comment]
Great idea, and thanks for putting in the legwork to get this working @indigoxela!

**Comment by indigoxela** [comment]
Thanks everyone for your feedback, the PR has been merged.
